# Generated by Django 4.2 on 2024-11-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='活动名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='活动内容')),
                ('score', models.IntegerField(default=0, verbose_name='分数')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动管理',
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('earned_score', models.IntegerField(default=0, verbose_name='获得分数')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动记录',
                'verbose_name_plural': '活动记录管理',
            },
        ),
    ]
